### ISSUE TITLE
请问基于monodle的CaDDN精度如何？

### ISSUE THREAD

**Issue by Senwang98** [czy341181/CaDDN_czy#1]
hi, @czy341181 
搜索caddn看到你的复现，请问这个精度如何复现的？

**Comment by czy341181** [comment]
这个代码还不太完善，之前有事情就没有更新这个仓库。  初步的实验比paper略微低1～2个AP，暂时也不太清楚问题在哪，可能是实现的有点问题

**Comment by Senwang98** [comment]
@czy341181 
我在caddn下面看到你的问题：https://github.com/TRAILab/CaDDN/issues/90
请问后面你是怎么处理这个问题的？因为我发现我这边用kitti原始数据直接跑效果也很怪，主要是天空看着很奇怪：
![image](https://user-images.githubusercontent.com/23122139/175066823-15eba48f-b143-4652-9662-6ebcd5f66b79.png)
你有成功转过velo到depth的经验吗？我对点云转深度图不是很了解，我想复现一个caddn提供的depth_2.zip这个文件

**Comment by czy341181** [comment]
需要调整一些参数，看一下ip_basic这个代码仓库的说明或者issue,调整一下参数就正常了，KITTI raw也是正常的我之前试过，具体什么参数有点记不太清了：）



关于velo转到depth，建议看看pseudo-lidar的reposity，是支持KITTI数据集的。&nbsp; 也可以看看patchnet（ECCV2020）的相关code部分


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "czy341181/CaDDN_czy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月22日(星期三) 晚上11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [czy341181/CaDDN_czy] 请问基于monodle的CaDDN精度如何？ (Issue #1)





 
@czy341181
 我在caddn下面看到你的问题：TRAILab/CaDDN#90
 请问后面你是怎么处理这个问题的？因为我发现我这边用kitti原始数据直接跑效果也很怪，主要是天空看着很奇怪：
 
 你有成功转过velo到depth的经验吗？我对点云转深度图不是很了解，我想复现一个caddn提供的depth_2.zip这个文件

**Comment by Senwang98** [comment]
@czy341181 
Okay，感谢老哥回复啊，我这边发现ip-basic换成multiscale这个配置就行。另外转深度图这个我找了一个脚本。
